
### 3. Stock A, Stock B, and Stock C have the following expected returns, standard deviations, and covariance matrix as follows. Given that the risk-free rate of return is 2%, 


#### 3.3 If your target return is 10%, discuss whether and why you should just invest in Stock A or in the efficient portfolio that you found above. (1 point)

#### 3.1 What is the expected return and standard deviation of the optimal portfolio? (1 point)

In [2]:
from scipy.optimize import minimize
import numpy as np
# The given expected returns and standard deviations
expected_returns = np.array([10, 15, 20])  # Expected returns for A, B, and C
std_devs = np.array([25, 35, 45])  # Standard deviations for A, B, and C
# The risk-free rate
risk_free_rate = 2

# The covariance matrix
cov_matrix = np.array([
    [625, 0, -337.5],
    [0, 1225, 866.25],
    [-337.5, 866.25, 2025]
])

# Constraints: sum of weights equals 1
constraints = ({'type': 'eq', 'fun': lambda x: np.sum(x) - 1})

# Initial guess for the weights (evenly distributed)
initial_weights = np.array([1/3, 1/3, 1/3])

# Bounds for weights: weights can range from 0 to 1
bounds = tuple((0, 1) for asset in range(len(expected_returns)))




In [3]:
# Define the objective function (negative Sharpe ratio)
def objective_function(weights, expected_returns, cov_matrix, risk_free_rate):
    portfolio_return = np.sum(weights * expected_returns)
    portfolio_volatility = np.sqrt(np.dot(weights.T, np.dot(cov_matrix, weights)))
    sharpe_ratio = (portfolio_return - risk_free_rate) / portfolio_volatility
    return -sharpe_ratio  # We will minimize this function, hence negative Sharpe ratio

# Optimize the weights to find the optimal portfolio that maximizes the Sharpe ratio
optimal_portfolio_result = minimize(
    objective_function,
    initial_weights,
    args=(expected_returns, cov_matrix, risk_free_rate),
    method='SLSQP',
    bounds=bounds,
    constraints=constraints
)

# The optimal weights
optimal_weights = optimal_portfolio_result.x

# Calculate the expected return and standard deviation of the optimal portfolio
optimal_portfolio_return = np.sum(optimal_weights * expected_returns)
optimal_portfolio_std_dev = np.sqrt(np.dot(optimal_weights.T, np.dot(cov_matrix, optimal_weights)))

optimal_weights, optimal_portfolio_return, optimal_portfolio_std_dev

(array([0.57467633, 0.09493068, 0.33039299]),
 13.778583301690421,
 19.09640998929537)

#### 3.2 Please form an efficient portfolio with an expected return of 10%. What would be your investment allocation across Stock A, Stock B, Stock C, and/or the risk-free asset? (1 point)

WA x E[RA] + WB x E[RB] + WC x E[RC] = E[R Portfolio]

where WA + WB + WC = 1

In [5]:
# Define the target return
target_return = 15  # 10%

# Constraints: expected return to be 10% and sum of weights to be 1
constraints = ({
    'type': 'eq',
    'fun': lambda weights: np.sum(weights) - 1
}, {
    'type': 'ineq',
    'fun': lambda weights: np.sum(weights * expected_returns) - 0.02
})


# Bounds for weights: weights can range from 0 to 1
bounds = tuple((0, 1) for _ in expected_returns)

# Optimize the weights to find the ones that give the expected return of 10%
result = minimize(
    lambda weights: -np.sum(weights * expected_returns),  # We want to maximize returns, hence minimize the negative
    initial_weights,
    method='SLSQP',
    bounds=bounds,
    constraints=constraints
)

# Assuming the rest of your code is unchanged and placed above this snippet.

# Calculate the optimal portfolio's Sharpe ratio using optimal weights
optimal_portfolio_sharpe_ratio = (optimal_portfolio_return - risk_free_rate) / optimal_portfolio_std_dev

# Returning the optimal weights, expected return, standard deviation, and Sharpe ratio of the optimal portfolio
optimal_weights, optimal_portfolio_return, optimal_portfolio_std_dev, optimal_portfolio_sharpe_ratio



(array([0.57467633, 0.09493068, 0.33039299]),
 13.778583301690421,
 19.09640998929537,
 0.616795686115505)

(array([1.00000000e+00, 7.69384556e-14, 0.00000000e+00]),
 24.999999999999027,
 True)